import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Download, FileText, Code2, AlertTriangle, Settings2, CheckCircle2 } from 'lucide-react';
import type { ForecastResponse } from '../lib/api';

export default function Export() {
  const [data, setData] = useState<ForecastResponse | null>(null);
  
  // Export Settings
  const [includeHistory, setIncludeHistory] = useState(true);
  const [includeIntervals, setIncludeIntervals] = useState(true);
  const [dateFormat, setDateFormat] = useState('YYYY-MM-DD');

  useEffect(() => {
    const saved = sessionStorage.getItem('laplace_forecast_data');
    if (saved) {
      try {
        setData(JSON.parse(saved));
      } catch (e) {
        // ignore
      }
    }
  }, []);

  if (!data) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center animate-in fade-in">
        <AlertTriangle className="text-accent-warning mb-4" size={48} />
        <h2 className="text-2xl font-bold mb-2">No Forecast Available</h2>
        <p className="text-base-secondary mb-6">Please run a forecast first before attempting to export data.</p>
        <Link to="/forecast" className="px-6 py-2 bg-base-primary text-white rounded-lg font-medium hover:bg-base-primary/90 transition-colors">
          Go to Forecast
        </Link>
      </div>
    );
  }

  const handleExportCSV = () => {
    const { forecast, history, model } = data;
    
    // Headers
    const headers = ['Date', 'Forecast'];
    if (includeIntervals) {
      headers.push('Lower_80', 'Upper_80');
    }
    
    let csvContent = `data:text/csv;charset=utf-8,${headers.join(',')}\n`;
    
    // History
    if (includeHistory && history) {
      for (let i = 0; i < history.dates.length; i++) {
        // For history, Forecast col has the actuals, bounds are empty
        const row = [
          history.dates[i],
          history.actual[i],
          includeIntervals ? '' : null,
          includeIntervals ? '' : null
        ].filter(v => v !== null).join(',');
        csvContent += row + '\n';
      }
    }
    
    // Forecast
    for (let i = 0; i < forecast.dates.length; i++) {
      const row = [
        forecast.dates[i],
        forecast.mean[i],
        includeIntervals ? forecast.lower[i] : null,
        includeIntervals ? forecast.upper[i] : null
      ].filter(v => v !== null).join(',');
      csvContent += row + '\n';
    }
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Laplace_${model}_Forecast.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const buildCodeSnippet = () => {
    const filename = `Laplace_${data.model}_Forecast.csv`;
    const intervalLines = includeIntervals
      ? `\nplt.fill_between(forecast.index, forecast['Lower_80'], forecast['Upper_80'], color='blue', alpha=0.2, label="80% Confidence")`
      : '';
    return `import pandas as pd
import matplotlib.pyplot as plt

# Load the Boardroom-Ready CSV
df = pd.read_csv('${filename}', parse_dates=['Date'])
df.set_index('Date', inplace=True)

# Separate History and Forecast
history = df[df['Lower_80'].isna()]
forecast = df[df['Lower_80'].notna()]

# Plot the projection
plt.figure(figsize=(12, 6))
plt.plot(history.index, history['Forecast'], label='Actual', color='black')
plt.plot(forecast.index, forecast['Forecast'], label='${data.model} Forecast', color='blue')${intervalLines}

plt.title('Laplace Engine: Time Series Projection')
plt.legend()
plt.tight_layout()
plt.show()`;
  };
  const codeSnippet = buildCodeSnippet();

  return (
    <div className="space-y-8 animate-in fade-in duration-500 pb-12">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-2">Export Studio</h1>
          <p className="text-base-secondary max-w-2xl">
            Customize and download the raw projections generated by <span className="font-bold text-base-primary">{data.model}</span>.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Export Settings Panel */}
        <div className="lg:col-span-1 space-y-6">
          <div className="p-6 bg-base-surface rounded-2xl border border-base-secondary/20">
            <div className="flex items-center gap-2 mb-6">
              <Settings2 size={20} className="text-base-secondary" />
              <h2 className="text-lg font-semibold">CSV Configuration</h2>
            </div>
            
            <div className="space-y-5">
              <label className="flex items-start gap-3 cursor-pointer group">
                <div className="relative flex items-center justify-center mt-0.5">
                  <input type="checkbox" className="peer sr-only" checked={includeHistory} onChange={() => setIncludeHistory(!includeHistory)} />
                  <div className="w-5 h-5 border-2 border-base-secondary/30 rounded flex items-center justify-center peer-checked:bg-accent-pulse peer-checked:border-accent-pulse transition-colors">
                    <CheckCircle2 size={14} className="text-white opacity-0 peer-checked:opacity-100 transition-opacity" />
                  </div>
                </div>
                <div>
                  <div className="font-medium text-base-primary group-hover:text-accent-pulse transition-colors">Include Historical Data</div>
                  <div className="text-xs text-base-secondary mt-0.5">Prepend the training sequence before the forecast.</div>
                </div>
              </label>

              <label className="flex items-start gap-3 cursor-pointer group">
                <div className="relative flex items-center justify-center mt-0.5">
                  <input type="checkbox" className="peer sr-only" checked={includeIntervals} onChange={() => setIncludeIntervals(!includeIntervals)} />
                  <div className="w-5 h-5 border-2 border-base-secondary/30 rounded flex items-center justify-center peer-checked:bg-accent-pulse peer-checked:border-accent-pulse transition-colors">
                    <CheckCircle2 size={14} className="text-white opacity-0 peer-checked:opacity-100 transition-opacity" />
                  </div>
                </div>
                <div>
                  <div className="font-medium text-base-primary group-hover:text-accent-pulse transition-colors">Include Confidence Intervals</div>
                  <div className="text-xs text-base-secondary mt-0.5">Export Lower and Upper 80% quantiles.</div>
                </div>
              </label>
              
              <div className="pt-2 border-t border-base-secondary/10">
                <label className="block text-sm font-medium mb-2">Date Format</label>
                <select 
                  className="w-full p-2.5 bg-white border border-base-secondary/20 rounded-lg text-sm outline-none focus:border-accent-pulse focus:ring-1 focus:ring-accent-pulse transition-all"
                  value={dateFormat}
                  onChange={(e) => setDateFormat(e.target.value)}
                >
                  <option value="YYYY-MM-DD">ISO 8601 (YYYY-MM-DD)</option>
                  <option value="MM/DD/YYYY">US Format (MM/DD/YYYY)</option>
                  <option value="DD/MM/YYYY">EU Format (DD/MM/YYYY)</option>
                </select>
              </div>
            </div>

            <button 
              onClick={handleExportCSV}
              className="mt-8 w-full flex items-center justify-center gap-2 px-6 py-3.5 bg-base-primary text-white rounded-xl font-bold hover:bg-base-primary/90 hover:-translate-y-0.5 transition-all shadow-md active:translate-y-0"
            >
              <Download size={20} />
              Download Boardroom CSV
            </button>
          </div>
          
          <div className="p-6 bg-[#111111] rounded-2xl border border-white/10 text-white relative overflow-hidden group">
            <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
              <FileText size={64} />
            </div>
            <h3 className="font-bold mb-2 relative z-10">Data Dictionary</h3>
            <ul className="text-sm text-gray-400 space-y-2 relative z-10">
              <li><span className="text-white font-medium">Date:</span> The temporal index.</li>
              <li><span className="text-white font-medium">Forecast:</span> The median / point projection (P50).</li>
              {includeIntervals && (
                <>
                  <li><span className="text-white font-medium">Lower_80:</span> Pessimistic bound (P10).</li>
                  <li><span className="text-white font-medium">Upper_80:</span> Optimistic bound (P90).</li>
                </>
              )}
            </ul>
          </div>
        </div>

        {/* Python Snippet Panel */}
        <div className="lg:col-span-2">
          <div className="h-full bg-base-surface rounded-2xl border border-base-secondary/20 overflow-hidden flex flex-col">
            <div className="px-6 py-4 border-b border-base-secondary/20 bg-white flex items-center gap-2">
              <Code2 size={20} className="text-base-secondary" />
              <h2 className="font-semibold">Reproducibility Snippet</h2>
            </div>
            <div className="p-6 flex-1 flex flex-col">
              <p className="text-sm text-base-secondary mb-4">
                Copy this Python snippet into your Jupyter Notebook to instantly load, parse, and visualize the exported dataset.
              </p>
              <div className="relative flex-1 bg-[#1E1E1E] rounded-xl border border-gray-800 p-4 overflow-auto font-mono text-[13px] leading-relaxed text-[#D4D4D4]">
                <button
                  onClick={() => navigator.clipboard.writeText(codeSnippet)}
                  className="absolute top-3 right-3 px-2 py-1 text-xs bg-white/10 hover:bg-white/20 text-gray-300 rounded transition-colors"
                >
                  Copy
                </button>
                <pre>{codeSnippet}</pre>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
