import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Download, AlertTriangle, Lightbulb, Rocket } from 'lucide-react';
import { Line, Area, ComposedChart, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from 'recharts';
import { runForecast, type ForecastRequest, type ForecastResponse } from '../lib/api';

const MODEL_COLORS: Record<string, string> = {
  'Chronos-Bolt-Small': '#0066FF',
  'ETS': '#FF6B00',
  'Theta': '#FFC700',
  'SeasonalNaive': '#FF2A3A'
};

export default function Forecast() {
  const [config, setConfig] = useState<ForecastRequest | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<ForecastResponse | null>(null);

  useEffect(() => {
    const saved = localStorage.getItem('laplace_dataset');
    const winner = localStorage.getItem('laplace_winner') || 'ETS';
    
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        const reqConfig = { ...parsed, model_name: winner, horizon: 12 };
        setConfig(reqConfig);
        loadForecast(reqConfig);
      } catch (e) {
        setLoading(false);
      }
    } else {
      setLoading(false);
    }
  }, []);

  const loadForecast = async (req: ForecastRequest) => {
    try {
      setLoading(true);
      const res = await runForecast(req);
      setData(res);
      sessionStorage.setItem('laplace_forecast_data', JSON.stringify(res));
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  if (!config) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center animate-in fade-in">
        <AlertTriangle className="text-accent-warning mb-4" size={48} />
        <h2 className="text-2xl font-bold mb-2">No Dataset Selected</h2>
        <p className="text-base-secondary mb-6">Please go back to Data Input and load a dataset first.</p>
        <Link to="/input" className="px-6 py-2 bg-base-primary text-white rounded-lg font-medium hover:bg-base-primary/90 transition-colors">
          Go to Data Input
        </Link>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-32 animate-in fade-in">
        <div className="w-10 h-10 border-4 border-base-surface border-t-accent-pulse rounded-full animate-spin mb-4" />
        <h3 className="font-medium">Projecting the Future...</h3>
        <p className="text-sm text-base-secondary">Generating intervals with {config.model_name}</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6 bg-accent-alert/10 text-accent-alert rounded-xl border border-accent-alert/20">
        <h3 className="font-bold mb-2">Forecast Failed</h3>
        <p>{error}</p>
        <button onClick={() => loadForecast(config)} className="mt-4 px-4 py-2 bg-white text-accent-alert rounded-md font-medium text-sm">Retry</button>
      </div>
    );
  }

  if (!data) return null;

  // Chart Data Preparation
  const chartData: any[] = [];
  const historyLen = data.history.dates.length;
  const cutoff = Math.max(0, historyLen - 60); // Show last 60 points of history

  for (let i = cutoff; i < historyLen; i++) {
    chartData.push({
      date: data.history.dates[i],
      actual: data.history.actual[i],
    });
  }

  // Connect the last historical point to the first forecast point
  const lastHistoryPoint = chartData[chartData.length - 1];
  
  // Forecast Data
  const h = data.horizon;
  for (let i = 0; i < h; i++) {
    chartData.push({
      date: data.forecast.dates[i],
      mean: data.forecast.mean[i],
      interval: [data.forecast.lower[i], data.forecast.upper[i]]
    });
  }

  const modelColor = MODEL_COLORS[data.model] || '#0066FF';
  const cutoffDate = lastHistoryPoint.date;

  return (
    <div className="space-y-8 animate-in fade-in duration-500 pb-12">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-2">Forecast</h1>
          <p className="text-base-secondary max-w-2xl">
            Future projection generated by the winning model <span className="font-bold text-base-primary">{data.model}</span>.
          </p>
        </div>
        <Link 
          to="/export"
          className="flex items-center gap-2 px-6 py-2.5 bg-base-primary text-white rounded-lg font-medium hover:bg-base-primary/90 transition-colors shadow-sm"
        >
          <Download size={18} />
          Proceed to Export Studio
        </Link>
      </div>

      {/* Main Forecast Chart */}
      <div className="p-6 bg-white border border-base-secondary/20 rounded-2xl h-[500px] flex flex-col">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Rocket size={20} className="text-accent-pulse" />
            <h2 className="text-lg font-semibold">{data.model} Projection (h={data.horizon})</h2>
          </div>
          <div className="flex items-center gap-4 text-sm">
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-full bg-[#111111]" />
              <span className="text-base-secondary">Historical</span>
            </div>
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-full" style={{backgroundColor: modelColor}} />
              <span className="text-base-secondary">Expected Forecast</span>
            </div>
            <div className="flex items-center gap-1.5">
              <div className="w-4 h-4 rounded-sm opacity-20" style={{backgroundColor: modelColor}} />
              <span className="text-base-secondary">80% Confidence Interval</span>
            </div>
          </div>
        </div>

        <ResponsiveContainer width="100%" height="100%">
          <ComposedChart data={chartData} margin={{ top: 20, right: 30, left: 0, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E5EA" />
            <XAxis 
              dataKey="date" 
              tick={{fontSize: 10, fill: '#6E6E73'}} 
              axisLine={false}
              tickLine={false}
              minTickGap={30}
            />
            <YAxis 
              tick={{fontSize: 10, fill: '#6E6E73'}} 
              axisLine={false}
              tickLine={false}
              domain={['auto', 'auto']}
              width={40}
            />
            <Tooltip 
              contentStyle={{ fontSize: '12px', borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
              labelStyle={{ fontWeight: 'bold', marginBottom: '4px', color: '#111111' }}
            />
            
            <ReferenceLine x={cutoffDate} stroke="#6E6E73" strokeDasharray="3 3" label={{ position: 'top', value: 'Today', fill: '#6E6E73', fontSize: 12 }} />

            {/* Confidence Interval Area */}
            <Area 
              type="monotone" 
              dataKey="interval" 
              stroke="none" 
              fill={modelColor} 
              fillOpacity={0.15} 
              activeDot={false}
            />

            {/* Historical Data */}
            <Line 
              type="monotone" 
              dataKey="actual" 
              stroke="#111111" 
              strokeWidth={2.5}
              dot={false}
              activeDot={{ r: 4, fill: '#111111', stroke: 'none' }}
              name="Actual"
            />
            
            {/* Forecast Mean */}
            <Line 
              type="monotone" 
              dataKey="mean" 
              stroke={modelColor} 
              strokeWidth={2.5}
              dot={false}
              activeDot={{ r: 4, fill: modelColor, stroke: 'none' }}
              name="Forecast"
              connectNulls
            />

          </ComposedChart>
        </ResponsiveContainer>
      </div>

      {/* Boardroom summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="p-6 bg-base-surface rounded-xl border border-base-secondary/20 flex flex-col justify-center">
          <Lightbulb className="text-accent-warning mb-3" size={24} />
          <h3 className="font-bold mb-1">Boardroom Ready</h3>
          <p className="text-sm text-base-secondary">
            Download the CSV to feed directly into your BI dashboards or presentation slides. The 80% confidence interval covers the most likely scenarios.
          </p>
        </div>
        <div className="p-6 bg-base-surface rounded-xl border border-base-secondary/20 flex flex-col justify-center">
          <div className="text-2xl font-bold text-base-primary mb-1">{data.horizon}</div>
          <h3 className="font-bold mb-1">Steps Ahead</h3>
          <p className="text-sm text-base-secondary">
            The model generated a projection for the next {data.horizon} periods based on the patterns learned in the validation phase.
          </p>
        </div>
        <div className="p-6 bg-base-surface rounded-xl border border-base-secondary/20 flex flex-col justify-center">
          <div className="w-8 h-8 rounded-full mb-3 flex items-center justify-center text-white font-bold" style={{backgroundColor: modelColor}}>
            {data.model.charAt(0)}
          </div>
          <h3 className="font-bold mb-1">Winning Architecture</h3>
          <p className="text-sm text-base-secondary">
            {data.model} was automatically selected because it achieved the lowest error margin during the holdout backtesting.
          </p>
        </div>
      </div>
    </div>
  );
}
